### ISSUE TITLE
Setup NVM and Node Engine in the repo

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6692]
It seems like we're using Node18 in all the CI workflows, so lets just make that the standard by setting up nvm in the repo and refer to that in CI instead of hard coding it.

- [Example nvmrc file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.nvmrc)
- [Example node (and yarn) engine setup](https://github.com/department-of-veterans-affairs/vets-website/blob/main/package.json#L240)
- [Example of nvm in CI](https://github.com/actions/setup-node)

**Definition of Done**

- [x] .nvmrc file is present in the root of our repo
- [x] node engine is set up in the root package.json file
- [x] All workflows function and use the .nvmrc file to set up node
- [x] All tests and builds still work

**Comment by timwright12** [comment]
**For CI:**

```
      - name: Get Node version
        id: get-node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}
```
